### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/float64-epsilon-difference#1]
This implementation shares similar behavior to [Boost](https://github.com/boostorg/math/blob/develop/include/boost/math/special_functions/relative_difference.hpp#L123), where, when converting a unitless relative difference to a relative difference in units of epsilon, if the conversion will overflow, the maximum double is returned. This does create an equivalency region where any value between `MAX_VALUE*EPS` and `MAX_VALUE` all share the same epsilon difference. However, one could argue that this difference is "closer" to the "truth" than returning `infinity`.

Your thoughts?

Dependent on math-io/relative-difference#1.

**Comment by Planeshifter** [comment]
I think the choice is sensible. Looked through the code, didn't find anything. Package should be ready to land.

**Comment by kgryte** [comment]
Awesome. Thanks for reviewing!
